import Head from "next/head";
import { PostList, PostForm } from "~/components";
import { trpc } from "~/utils/trpc";

export default function Home() {
  const postsQuery = trpc.post.list.useQuery({ limit: 5 });

  return (
    <div>
      <Head>
        <title>The Next Blogger</title>
        <meta name="description" content="Generated by create next app" />z
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-row justify-center items-center">
        <div className="flex flex-col p-8 w-8/12">
          {postsQuery.isLoading && <div>Loading blog posts</div>}
          {postsQuery.isError && (
            <div>There is an error loading the blog posts</div>
          )}
          {postsQuery.data && <PostList posts={postsQuery.data?.items} />}

          <PostForm />
        </div>
      </div>
    </div>
  );
}
