import Head from "next/head";
import Image from "next/image";
import { trpc } from "~/utils/trpc";
import styles from "../../styles/Home.module.css";

export default function Home() {
  const utils = trpc.useContext();
  const postsQuery = trpc.post.list.useQuery({ limit: 5 });
  const addPostMutation = trpc.post.add.useMutation({
    async onSuccess() {
      await utils.post.list.invalidate;
    },
  });

  console.log(postsQuery);

  // add hardcoded data
  const handleAddPost = async () => {
    try {
      await addPostMutation.mutate({
        title: "This is the title",
        content:
          "This is the content of the blogpost. It is gonna be hardcoded for now",
      });
    } catch (error) {
      console.error({ error }, "Failed to add a post");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>The Next Blogger</title>
        <meta name="description" content="Generated by create next app" />z
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">the Next blog!</a>
        </h1>
        <div>
          <button onClick={handleAddPost}>Add a post</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
